// <auto-generated />
namespace ResidualCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2221q : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2221q));
        
        string IMigrationMetadata.Id
        {
            get { return "201812310316233_2221q"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
