// <auto-generated />
namespace ResidualCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class x222dd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(x222dd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812300103413_x222dd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
